//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProductWS.ProductWSConsumer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunSonuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UrunSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UrunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        private System.Nullable<decimal> FiyatField;
        
        private System.Nullable<short> StokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UrunID {
            get {
                return this.UrunIDField;
            }
            set {
                if ((this.UrunIDField.Equals(value) != true)) {
                    this.UrunIDField = value;
                    this.RaisePropertyChanged("UrunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((this.FiyatField.Equals(value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<short> Stok {
            get {
                return this.StokField;
            }
            set {
                if ((this.StokField.Equals(value) != true)) {
                    this.StokField = value;
                    this.RaisePropertyChanged("Stok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductWSConsumer.ProductWSSoap")]
    public interface ProductWSSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki HelloWorldResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientProductWS.ProductWSConsumer.HelloWorldResponse HelloWorld(ClientProductWS.ProductWSConsumer.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.HelloWorldResponse> HelloWorldAsync(ClientProductWS.ProductWSConsumer.HelloWorldRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki urunGetirResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/urunGetir", ReplyAction="*")]
        ClientProductWS.ProductWSConsumer.urunGetirResponse urunGetir(ClientProductWS.ProductWSConsumer.urunGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/urunGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.urunGetirResponse> urunGetirAsync(ClientProductWS.ProductWSConsumer.urunGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientProductWS.ProductWSConsumer.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientProductWS.ProductWSConsumer.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class urunGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="urunGetir", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.urunGetirRequestBody Body;
        
        public urunGetirRequest() {
        }
        
        public urunGetirRequest(ClientProductWS.ProductWSConsumer.urunGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class urunGetirRequestBody {
        
        public urunGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class urunGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="urunGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.urunGetirResponseBody Body;
        
        public urunGetirResponse() {
        }
        
        public urunGetirResponse(ClientProductWS.ProductWSConsumer.urunGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class urunGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ClientProductWS.ProductWSConsumer.UrunSonuc> urunGetirResult;
        
        public urunGetirResponseBody() {
        }
        
        public urunGetirResponseBody(System.Collections.Generic.List<ClientProductWS.ProductWSConsumer.UrunSonuc> urunGetirResult) {
            this.urunGetirResult = urunGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWSSoapChannel : ClientProductWS.ProductWSConsumer.ProductWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWSSoapClient : System.ServiceModel.ClientBase<ClientProductWS.ProductWSConsumer.ProductWSSoap>, ClientProductWS.ProductWSConsumer.ProductWSSoap {
        
        public ProductWSSoapClient() {
        }
        
        public ProductWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductWS.ProductWSConsumer.HelloWorldResponse ClientProductWS.ProductWSConsumer.ProductWSSoap.HelloWorld(ClientProductWS.ProductWSConsumer.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientProductWS.ProductWSConsumer.HelloWorldRequest inValue = new ClientProductWS.ProductWSConsumer.HelloWorldRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.HelloWorldRequestBody();
            ClientProductWS.ProductWSConsumer.HelloWorldResponse retVal = ((ClientProductWS.ProductWSConsumer.ProductWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.HelloWorldResponse> ClientProductWS.ProductWSConsumer.ProductWSSoap.HelloWorldAsync(ClientProductWS.ProductWSConsumer.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.HelloWorldResponse> HelloWorldAsync() {
            ClientProductWS.ProductWSConsumer.HelloWorldRequest inValue = new ClientProductWS.ProductWSConsumer.HelloWorldRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.HelloWorldRequestBody();
            return ((ClientProductWS.ProductWSConsumer.ProductWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductWS.ProductWSConsumer.urunGetirResponse ClientProductWS.ProductWSConsumer.ProductWSSoap.urunGetir(ClientProductWS.ProductWSConsumer.urunGetirRequest request) {
            return base.Channel.urunGetir(request);
        }
        
        public System.Collections.Generic.List<ClientProductWS.ProductWSConsumer.UrunSonuc> urunGetir() {
            ClientProductWS.ProductWSConsumer.urunGetirRequest inValue = new ClientProductWS.ProductWSConsumer.urunGetirRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.urunGetirRequestBody();
            ClientProductWS.ProductWSConsumer.urunGetirResponse retVal = ((ClientProductWS.ProductWSConsumer.ProductWSSoap)(this)).urunGetir(inValue);
            return retVal.Body.urunGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.urunGetirResponse> ClientProductWS.ProductWSConsumer.ProductWSSoap.urunGetirAsync(ClientProductWS.ProductWSConsumer.urunGetirRequest request) {
            return base.Channel.urunGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.urunGetirResponse> urunGetirAsync() {
            ClientProductWS.ProductWSConsumer.urunGetirRequest inValue = new ClientProductWS.ProductWSConsumer.urunGetirRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.urunGetirRequestBody();
            return ((ClientProductWS.ProductWSConsumer.ProductWSSoap)(this)).urunGetirAsync(inValue);
        }
    }
}
